# For Fleet Premium, the default.yml file updates policies and queries that run on all hosts ("All teams"). Controls and agent options are updated for hosts on "No team."

policies:
  - path: ./lib/mac/policies/mac-operating-system-up-to-date.yml
queries:
  - path: ./lib/all/queries/collect-fleetd-update-channels-queries.yml
agent_options:
  path: ./lib/all/agent-options.yml
controls:
org_settings:
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: "Allen & Emily"
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"
software:
