# For Fleet Premium, the default.yml file updates policies and queries that run on all hosts ("All teams"). Controls and agent options are updated for hosts on "No team."

policies:
  - path: ./lib/mac/policies/mac-operating-system-up-to-date.yml
  - path: ./lib/mac/policies/mac-google-chrome-up-to-date.yml
  - path: ./lib/win/policies/win-google-chrome-up-to-date.yml
queries:
agent_options:
  path: ./lib/all/agent-options.yml
controls:
  scripts:
org_settings:
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: "Allen & Emily"
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"
software:
  packages:
    - url: https://github.com/allenhouchins/elphael-fleet-packages/raw/refs/heads/main/GoogleChrome-129.0.6668.71.pkg?download=1
      self_service: true