# For Fleet Premium, the default.yml file updates policies and queries that run on all hosts ("All teams"). Controls and agent options are updated for hosts on "No team."

policies:
  - path: ./lib/mac/policies/mac-operating-system-up-to-date.yml
  - path: ./lib/mac/policies/mac-google-chrome-up-to-date.yml
  - path: ./lib/win/policies/win-google-chrome-up-to-date.yml
  - path: ./lib/mac/policies/mac-firefox-up-to-date.yml
  - path: ./lib/mac/policies/mac-apple-intelligence-check.yml
queries:
agent_options:
  path: ./lib/all/agent-options.yml
controls:
  windows_enabled_and_configured: true
  macos_migration: # Available in Fleet Premium
    enable: true
    mode: voluntary
    webhook_url: https://rough-silence-1075.tines.com/webhook/9c31a8867763940219b0f32203d70279/d6c4426cd73846de170bbf36effecbd7
org_settings:
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: "Brace of the Haligtree"
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"
software:
  packages:
  app_store_apps: 