name: "Automated policy updater: Operating system up to date (macOS)"

on:
  schedule:
    - cron: '*/10 * * * *'  # Run daily at noon
  workflow_dispatch:     # Allow manual trigger

jobs:
  update-macos-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Run macOS version update script
        run: |
          chmod +x ./.github/scripts/macos_version_updater.sh
          ./.github/scripts/macos_version_updater.sh
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}  # Use GitHub token for authentication