name: "Policy Updater: macOS - Operating System Up to Date"

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:       # Allow manual trigger

jobs:
  update-macos-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # ✅ Allows pushing changes
      pull-requests: write   # ✅ Allows creating pull requests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Prevent checkout action from overriding authentication

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Run macOS version update script
        run: |
          chmod +x ./.github/scripts/macos_version_policy_updater.sh
          ./.github/scripts/macos_version_policy_updater.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ✅ Use the built-in GitHub Actions token
